model_config:
  in_channels: 3
  out_channels: 1
  init_features: 64
  depth: 4
  attention_mode: additive
  dropout: 0.1
optimizer_config:
  name: adamw
  lr: 0.0001
  weight_decay: 1.0e-05
  betas:
  - 0.9
  - 0.999
scheduler_config:
  name: reduce_lr_on_plateau
  mode: max
  factor: 0.5
  patience: 5
  min_lr: 1.0e-06
  monitor: val_prauc
loss_config:
  loss_type: focal_tversky
  focal_tversky_weight: 0.7
  focal_weight: 0.3
  tversky_alpha: 0.7
  tversky_beta: 0.3
  tversky_gamma: 0.75
  focal_alpha: 0.25
  focal_gamma: 2.0
  smooth: 1.0
threshold_optimization_config:
  enabled: true
  min_threshold: 0.1
  max_threshold: 0.9
  num_candidates: 10
